// flow-typed signature: 70909ecd691052f7e7b7d5524ea674f6
// flow-typed version: <<STUB>>/d3-delaunay_v4.1.5/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-delaunay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-delaunay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-delaunay/dist/d3-delaunay' {
  declare module.exports: any;
}

declare module 'd3-delaunay/dist/d3-delaunay.min' {
  declare module.exports: any;
}

declare module 'd3-delaunay/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-delaunay/src/delaunay' {
  declare module.exports: any;
}

declare module 'd3-delaunay/src/index' {
  declare module.exports: any;
}

declare module 'd3-delaunay/src/path' {
  declare module.exports: any;
}

declare module 'd3-delaunay/src/polygon' {
  declare module.exports: any;
}

declare module 'd3-delaunay/src/voronoi' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-delaunay/dist/d3-delaunay.js' {
  declare module.exports: $Exports<'d3-delaunay/dist/d3-delaunay'>;
}
declare module 'd3-delaunay/dist/d3-delaunay.min.js' {
  declare module.exports: $Exports<'d3-delaunay/dist/d3-delaunay.min'>;
}
declare module 'd3-delaunay/rollup.config.js' {
  declare module.exports: $Exports<'d3-delaunay/rollup.config'>;
}
declare module 'd3-delaunay/src/delaunay.js' {
  declare module.exports: $Exports<'d3-delaunay/src/delaunay'>;
}
declare module 'd3-delaunay/src/index.js' {
  declare module.exports: $Exports<'d3-delaunay/src/index'>;
}
declare module 'd3-delaunay/src/path.js' {
  declare module.exports: $Exports<'d3-delaunay/src/path'>;
}
declare module 'd3-delaunay/src/polygon.js' {
  declare module.exports: $Exports<'d3-delaunay/src/polygon'>;
}
declare module 'd3-delaunay/src/voronoi.js' {
  declare module.exports: $Exports<'d3-delaunay/src/voronoi'>;
}
