// flow-typed signature: 91a777f1c6b2645413da943ecd38fbbf
// flow-typed version: <<STUB>>/d3-polygon_v1.0.5/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-polygon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-polygon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-polygon/dist/d3-polygon' {
  declare module.exports: any;
}

declare module 'd3-polygon/dist/d3-polygon.min' {
  declare module.exports: any;
}

declare module 'd3-polygon/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-polygon/src/area' {
  declare module.exports: any;
}

declare module 'd3-polygon/src/centroid' {
  declare module.exports: any;
}

declare module 'd3-polygon/src/contains' {
  declare module.exports: any;
}

declare module 'd3-polygon/src/cross' {
  declare module.exports: any;
}

declare module 'd3-polygon/src/hull' {
  declare module.exports: any;
}

declare module 'd3-polygon/src/index' {
  declare module.exports: any;
}

declare module 'd3-polygon/src/length' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-polygon/dist/d3-polygon.js' {
  declare module.exports: $Exports<'d3-polygon/dist/d3-polygon'>;
}
declare module 'd3-polygon/dist/d3-polygon.min.js' {
  declare module.exports: $Exports<'d3-polygon/dist/d3-polygon.min'>;
}
declare module 'd3-polygon/rollup.config.js' {
  declare module.exports: $Exports<'d3-polygon/rollup.config'>;
}
declare module 'd3-polygon/src/area.js' {
  declare module.exports: $Exports<'d3-polygon/src/area'>;
}
declare module 'd3-polygon/src/centroid.js' {
  declare module.exports: $Exports<'d3-polygon/src/centroid'>;
}
declare module 'd3-polygon/src/contains.js' {
  declare module.exports: $Exports<'d3-polygon/src/contains'>;
}
declare module 'd3-polygon/src/cross.js' {
  declare module.exports: $Exports<'d3-polygon/src/cross'>;
}
declare module 'd3-polygon/src/hull.js' {
  declare module.exports: $Exports<'d3-polygon/src/hull'>;
}
declare module 'd3-polygon/src/index.js' {
  declare module.exports: $Exports<'d3-polygon/src/index'>;
}
declare module 'd3-polygon/src/length.js' {
  declare module.exports: $Exports<'d3-polygon/src/length'>;
}
